live_config_reload = true

[window]
opacity = 0.85
dynamic_padding = false
decorations = "buttonless"

[font]
size = 22.0


[window.padding]
x = 18
y = 16

[font.normal]
family = "PragmataPro Mono Liga"
style = "Regular"
