live_config_reload = true

[window]
opacity = 0.85
dynamic_padding = false
decorations = "buttonless"

[font]
size = 22.0
use_thin_strokes = true

[window.padding]
x = 18
y = 16

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
